proyectoLaravel/routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/prueba', [App\Http\Controllers\ProductController::class, 'index']);
Route::get('/prueba2', [App\Http\Controllers\PublicationController::class, 'show']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\PublicationController::class, 'index'])->name('home');




Route::resource('layouts', PublicationController::class);

Route::resource('comments', CommentController::class);

Route::get('/createcomment', [App\Http\Controllers\PublicationController::class, 'createcomment']);

proyectoLaravel/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar--danger bg--danger">
  <a class="btn btn-outline-success my-2 my-sm-0" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cerrar Sesión') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>

</nav>
<main class="py-4">
            @yield('content')
        </main>
</body>
</html>

proyectoLaravel/resources/views/layouts/create.blade.php
@extends('layouts.layout')
  
@section('content')
<body>
<div class="container">
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Publicar</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('layouts.index') }}"> Atras</a>
            </div>
        </div>
    </div>

<form action="{{ route('layouts.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Perfil:</strong>
                <input type="text" name="title" class="form-control" placeholder="Titulo de la publicación">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Contenido:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Crear</button>
        </div>
    </div>
   
    </form>
</div>
</body>
@endsection

proyectoLaravel/resources/views/layouts/createcomment.blade.php
@extends('layouts.layout')
  
@section('content')
<body>
<div class="container">
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Comentar</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('layouts.index') }}"> Atras</a>
            </div>
        </div>
    </div>

<form action="{{ route('layouts.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Comentario:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Publicar</button>
        </div>
    </div>
   
    </form>
</div>
</body>
@endsection

proyectoLaravel/resources/views/layouts/edit.blade.php
@extends('layouts.layout')
   
@section('content')
<body>
<div class="container">
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Actualizar publicación</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('layouts.index') }}"> Atras</a>
            </div>
        </div>
    </div>
 
    <form action="{{ route('layouts.update',$layout->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Titulo:</strong>
                    <input type="text" name="title" value="{{ $layout->title }}" class="form-control" placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Contenido:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ $layout->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </div>
   
    </form>
</div>
</body>
    
@endsection

proyectoLaravel/resources/views/layouts/index.blade.php
@extends('layouts.app')
 
@section('content')
<body>
    
<div class="container">
    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('layouts.create') }}"> Nueva publicación</a>
            </div>
        </div>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Titulo</th>
            <th>Publicación</th>
            <th width="280px">Acciónes</th>
        </tr>
        @foreach ($data as $key => $value)
        <tr>
            <td>{{ $value->title }}</td>
            <td>{{ \Str::limit($value->description, 100) }}</td>
            <td>
                <form action="{{ route('layouts.destroy',$value->id) }}" method="POST">   
                    <a class="btn btn-info" href="{{ route('layouts.show',$value->id) }}">Ver</a>    
                    <a class="btn btn-primary" href="{{ route('layouts.edit',$value->id) }}">Cambiar</a>   
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  

</div>

</body>

    {!! $data->links() !!}      
@endsection

proyectoLaravel/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
@extends('layouts.app')
</div>
   
</body>
</html>

proyectoLaravel/resources/views/layouts/show.blade.php
@extends('layouts.layout')
  
@section('content')
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Comentarios</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('layouts.index') }}"> Atras</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Titulo:</strong>
                {{ $layout->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Contenido:</strong>
                {{ $layout->description }}  
            </div>
        </div>
        <div class="container">
    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ url('/createcomment') }}"> Nueva comentario</a>
            </div>
        </div>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Comentarios</th>
        </tr>
        @foreach ($comments as $key => $value)
        <tr>
            <td>{{ $value->content }}</td>
        </tr>
        @endforeach
    </table>  
</div>
    </div>
    </div>
</body>
@endsection